### ISSUE TITLE
Editor weirdness 

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/groupthink#131]
Lately, the editor is doing some weird stuff when I'm using it in Chrome on Android. It likes to delete spaces between words a lot. Sometimes, when I try to re-add the space, it gets deleted again but a space is added after the joined words. I did a video to illustrate what happens - look especially at what happens when I tap space.

https://youtu.be/90xsHDSIWhA

**Comment by jt-nti** [comment]
This looks similar to a problem someone just pinged me about on the Eastleigh Manifesto...

> Tried adding a new file, every time I press space, when adding text it just duplicates the word, so if I were to type "hello" then space it changes to "hellohello" weird and frustrating!

**Comment by jt-nti** [comment]
Same thing happens on https://simplemde.com/ so it doesn't look like a groupthink issue.

Unfortunately it looks like the current markdown editor ins't maintained any more, but there is a fork which does work on android...

https://easymde.tk/

Would it be ok to switch?

**Comment by Floppy** [comment]
Ah, good catch! I'm not attached to SimpleMDE and if it's not maintained, then we could swap over to something else, no problem.

**Comment by Floppy** [comment]
@jt-nti @philipjohn I've changed to EasyMDE now, see if that fixes it!

**Comment by jt-nti** [comment]
Nice, thanks! Seems to be working better!

**Comment by Floppy** [comment]
Amazing! I'm gonna close this as it sounds very much like what @philipjohn had, so I think we're good. Huge thanks for debugging it and finding the solution @jt-nti, it would have been a long time before I managed to spend time doing that.

**Comment by jt-nti** [comment]
No problem, thanks for getting the new editor in so quickly @Floppy
