### ISSUE TITLE
Error: code=H14 desc="No web processes running" after deploying to Heroku

### ISSUE THREAD

**Issue by dopoto** [openpolitics/groupthink#371]
I'm following the setup instructions in README.md. 

Right after the initial deployment in Heroku, the app works, and the following is shown in Heroku Dashboard > Resources > Dynos:

```
web bundle exec bin/rails server -p $PORT -e $RAILS_NEW  ON
worker bundle exec sidekiq -q default -q mailers -c 10  ON
```
But, after I set up automatic deployment from GitHub and I do a redeployment, the following happens:

1. App no longer works, the following error is shown in logs: 

`Error: code=H14 desc="No web processes running"`

2. My Heroku dashboard > Resources > Dynos now says:

```
This app has no process types yet
Add a Procfile to your app in order to define its process types. 
Learn more: https://devcenter.heroku.com/articles/procfile
```

My template fork is here: https://github.com/dopoto/opt2

Is there anything that should be added in the configuration maybe to solve this issue?

**Comment by Floppy** [comment]
I suspect that in the autodeployment configuration, you've told it to autodeploy from your template fork, not from the groupthink repository. That's unclear in the README, sorry, I'll fix that. In general the whole separation of the template and the groupthink app is pretty unintuitive - I'll see if I can make it more obvious how it all fits together.
