### ISSUE TITLE
Add "Comment and vote" button to proposals for logged out users

### ISSUE THREAD

**Issue by jt-nti** [openpolitics/groupthink#620]
A few people have been confused about why they cannot do anything with proposals on the Eastleigh manifesto and I think it's because they haven't logged in. The sign in link isn't that obvious, and is not a great CTA either.

Would it be possible to add a prominent "Comment and vote" button to proposals which takes you to the `/edit` (sign in with GitHub page)? It would obviously need to end up routing them to the right proposal after signing in.

**Comment by Floppy** [comment]
Good idea! I'll see if I can get it added soon.

**Comment by jt-nti** [comment]
Fantastic, thanks!
