### ISSUE TITLE
Error resizing dynos: Couldn't find that process type (worker)

### ISSUE THREAD

**Issue by tyumru** [openpolitics/groupthink#705]
First of all, thank you all for this awesome project. 

I am trying to clone the project via heroku deploy button. After several trial&error iterations, I have finally managed to set all the env variables correctly. Now the build log seems fine and throws no errors. But during the `Run scripts & scale dynos` step I keep receiving the following:

> Error resizing dynos: Couldn't find that process type (worker).

Since the build doesn't fail, this problem seems to be related to heroku, rather than groupthink, but I couldn't understand why heroku is unable to recognize worker process type.

 Any suggestions for a workaround would be great!

Build log in any case:

> -----> Ruby app detected
> -----> Installing bundler 2.0.2
> -----> Removing BUNDLED WITH version in the Gemfile.lock
> -----> Compiling Ruby/Rails
> -----> Using Ruby version: ruby-2.7.1
> -----> Installing dependencies using bundler 2.0.2
>        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
>        [DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set deployment 'true'`, and stop using this flag
>        [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
>        [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development:test'`, and stop using this flag
>        [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`
>        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
>        Fetching gem metadata from https://rubygems.org/..........
>        Fetching rake 13.0.1
>        Installing rake 13.0.1
>        Fetching concurrent-ruby 1.1.6
>        Fetching minitest 5.14.1
>        Fetching thread_safe 0.3.6
>        Installing thread_safe 0.3.6
>        Installing minitest 5.14.1
>        Installing concurrent-ruby 1.1.6
>        Fetching zeitwerk 2.3.0
>        Fetching builder 3.2.4
>        Installing zeitwerk 2.3.0
>        Installing builder 3.2.4
>        Fetching erubi 1.9.0
>        Fetching mini_portile2 2.4.0
>        Installing erubi 1.9.0
>        Installing mini_portile2 2.4.0
>        Fetching crass 1.0.6
>        Installing crass 1.0.6
>        Fetching rack 2.2.2
>        Fetching nio4r 2.5.2
>        Installing nio4r 2.5.2 with native extensions
>        Installing rack 2.2.2
>        Fetching websocket-extensions 0.1.4
>        Installing websocket-extensions 0.1.4
>        Fetching mimemagic 0.3.5
>        Fetching mini_mime 1.0.2
>        Installing mini_mime 1.0.2
>        Installing mimemagic 0.3.5
>        Fetching public_suffix 4.0.5
>        Installing public_suffix 4.0.5
>        Using bundler 2.1.4
>        Fetching cancancan 3.1.0
>        Fetching bcrypt 3.1.13
>        Installing bcrypt 3.1.13 with native extensions
>        Installing cancancan 3.1.0
>        Fetching coffee-script-source 1.12.2
>        Installing coffee-script-source 1.12.2
>        Fetching execjs 2.7.0
>        Installing execjs 2.7.0
>        Fetching method_source 1.0.0
>        Installing method_source 1.0.0
>        Fetching thor 1.0.1
>        Installing thor 1.0.1
>        Fetching deep_merge 1.2.1
>        Installing deep_merge 1.2.1
>        Fetching dry-equalizer 0.3.0
>        Installing dry-equalizer 0.3.0
>        Fetching dry-initializer 3.0.3
>        Installing dry-initializer 3.0.3
>        Fetching dry-inflector 0.2.0
>        Installing dry-inflector 0.2.0
>        Fetching orm_adapter 0.5.0
>        Installing orm_adapter 0.5.0
>        Fetching multipart-post 2.1.1
>        Installing multipart-post 2.1.1
>        Fetching ffi 1.12.2
>        Installing ffi 1.12.2 with native extensions
>        Fetching github-markup 3.0.4
>        Installing github-markup 3.0.4
>        Fetching temple 0.8.2
>        Installing temple 0.8.2
>        Fetching tilt 2.0.10
>        Installing tilt 2.0.10
>        Fetching hashie 4.1.0
>        Installing hashie 4.1.0
>        Fetching jwt 2.2.1
>        Installing jwt 2.2.1
>        Fetching kaminari-core 1.2.1
>        Installing kaminari-core 1.2.1
>        Fetching memoist 0.16.2
>        Installing memoist 0.16.2
>        Fetching multi_json 1.14.1
>        Installing multi_json 1.14.1
>        Fetching multi_xml 0.6.0
>        Installing multi_xml 0.6.0
>        Fetching nested_form 0.3.2
>        Installing nested_form 0.3.2
>        Fetching pg 1.2.3
>        Installing pg 1.2.3 with native extensions
>        Fetching remotipart 1.4.4
>        Installing remotipart 1.4.4
>        Fetching redcarpet 3.5.0
>        Installing redcarpet 3.5.0 with native extensions
>        Fetching rinku 2.0.6
>        Installing rinku 2.0.6 with native extensions
>        Fetching turbolinks-source 5.2.0
>        Installing turbolinks-source 5.2.0
>        Fetching tzinfo 1.2.7
>        Installing tzinfo 1.2.7
>        Fetching nokogiri 1.10.9
>        Installing nokogiri 1.10.9 with native extensions
>        Fetching i18n 1.8.2
>        Installing i18n 1.8.2
>        Fetching bugsnag 6.13.1
>        Installing bugsnag 6.13.1
>        Fetching dry-core 0.4.9
>        Installing dry-core 0.4.9
>        Fetching sucker_punch 2.1.2
>        Installing sucker_punch 2.1.2
>        Fetching websocket-driver 0.7.2
>        Installing websocket-driver 0.7.2 with native extensions
>        Fetching rack-test 1.1.0
>        Installing rack-test 1.1.0
>        Fetching warden 1.2.8
>        Installing warden 1.2.8
>        Fetching request_store 1.5.0
>        Installing request_store 1.5.0
>        Fetching sprockets 3.7.2
>        Installing sprockets 3.7.2
>        Fetching mail 2.7.1
>        Installing mail 2.7.1
>        Fetching addressable 2.7.0
>        Installing addressable 2.7.0
>        Fetching marcel 0.3.3
>        Installing marcel 0.3.3
>        Fetching coffee-script 2.4.1
>        Installing coffee-script 2.4.1
>        Fetching uglifier 4.2.0
>        Installing uglifier 4.2.0
>        Fetching faraday 1.0.1
>        Installing faraday 1.0.1
>        Fetching puma 4.3.5
>        Installing puma 4.3.5 with native extensions
>        Fetching haml 5.1.2
>        Installing haml 5.1.2
>        Fetching omniauth 1.9.1
>        Installing omniauth 1.9.1
>        Fetching sassc 2.0.1
>        Fetching turbolinks 5.2.1
>        Installing turbolinks 5.2.1
>        Installing sassc 2.0.1 with native extensions
>        Fetching activesupport 6.0.3.1
>        Installing activesupport 6.0.3.1
>        Fetching dry-configurable 0.11.5
>        Installing dry-configurable 0.11.5
>        Fetching dry-logic 1.0.6
>        Installing dry-logic 1.0.6
>        Fetching oauth2 1.4.4
>        Installing oauth2 1.4.4
>        Fetching sawyer 0.8.2
>        Installing sawyer 0.8.2
>        Fetching loofah 2.5.0
>        Installing loofah 2.5.0
>        Fetching rack-pjax 1.1.0
>        Installing rack-pjax 1.1.0
>        Fetching rails-dom-testing 2.0.3
>        Installing rails-dom-testing 2.0.3
>        Fetching globalid 0.4.2
>        Installing globalid 0.4.2
>        Fetching activemodel 6.0.3.1
>        Installing activemodel 6.0.3.1
>        Fetching jbuilder 2.10.0
>        Installing jbuilder 2.10.0
>        Fetching dry-container 0.7.2
>        Installing dry-container 0.7.2
>        Fetching omniauth-oauth2 1.6.0
>        Installing omniauth-oauth2 1.6.0
>        Fetching octokit 4.18.0
>        Installing octokit 4.18.0
>        Fetching rails-html-sanitizer 1.3.0
>        Installing rails-html-sanitizer 1.3.0
>        Fetching activejob 6.0.3.1
>        Installing activejob 6.0.3.1
>        Fetching activerecord 6.0.3.1
>        Installing activerecord 6.0.3.1
>        Fetching activemodel-serializers-xml 1.0.2
>        Installing activemodel-serializers-xml 1.0.2
>        Fetching dry-types 1.4.0
>        Installing dry-types 1.4.0
>        Fetching omniauth-github 1.4.0
>        Installing omniauth-github 1.4.0
>        Fetching actionview 6.0.3.1
>        Installing actionview 6.0.3.1
>        Fetching kaminari-activerecord 1.2.1
>        Installing kaminari-activerecord 1.2.1
>        Fetching paper_trail 10.3.1
>        Installing paper_trail 10.3.1
>        Fetching dry-schema 1.5.1
>        Installing dry-schema 1.5.1
>        Fetching actionpack 6.0.3.1
>        Installing actionpack 6.0.3.1
>        Fetching kaminari-actionview 1.2.1
>        Installing kaminari-actionview 1.2.1
>        Fetching dry-validation 1.5.0
>        Installing dry-validation 1.5.0
>        Fetching actioncable 6.0.3.1
>        Installing actioncable 6.0.3.1
>        Fetching activestorage 6.0.3.1
>        Installing activestorage 6.0.3.1
>        Fetching actionmailer 6.0.3.1
>        Installing actionmailer 6.0.3.1
>        Fetching railties 6.0.3.1
>        Installing railties 6.0.3.1
>        Fetching omniauth-rails_csrf_protection 0.1.2
>        Installing omniauth-rails_csrf_protection 0.1.2
>        Fetching sprockets-rails 3.2.1
>        Installing sprockets-rails 3.2.1
>        Fetching kaminari 1.2.1
>        Installing kaminari 1.2.1
>        Fetching config 2.2.1
>        Installing config 2.2.1
>        Fetching actionmailbox 6.0.3.1
>        Fetching actiontext 6.0.3.1
>        Installing actionmailbox 6.0.3.1
>        Installing actiontext 6.0.3.1
>        Fetching coffee-rails 5.0.0
>        Installing coffee-rails 5.0.0
>        Fetching responders 3.0.0
>        Fetching font-awesome-rails 4.7.0.5
>        Installing responders 3.0.0
>        Installing font-awesome-rails 4.7.0.5
>        Fetching jquery-rails 4.4.0
>        Installing jquery-rails 4.4.0
>        Fetching jquery-ui-rails 6.0.1
>        Installing jquery-ui-rails 6.0.1
>        Fetching rails 6.0.3.1
>        Installing rails 6.0.3.1
>        Fetching devise 4.7.1
>        Installing devise 4.7.1
>        Fetching sassc-rails 2.1.2
>        Installing sassc-rails 2.1.2
>        Fetching rails_admin 2.0.2
>        Installing rails_admin 2.0.2
>        Bundle complete! 60 Gemfile dependencies, 112 gems now installed.
>        Gems in the groups development and test were not installed.
>        Bundled gems are installed into `./vendor/bundle`
>        Post-install message from i18n:
>        
>        HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
>        But that may break your application.
>        
>        If you are upgrading your Rails application from an older version of Rails:
>        
>        Please check your Rails app for 'config.i18n.fallbacks = true'.
>        If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
>        'config.i18n.fallbacks = [I18n.default_locale]'.
>        If not, fallbacks will be broken in your app by I18n 1.1.x.
>        
>        If you are starting a NEW Rails application, you can ignore this notice.
>        
>        For more info see:
>        https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
>        
>        Post-install message from config:
>        
>        Thanks for installing Config 🙏
>        Please consider donating to our open collective to help us maintain this project.
>        
>        
>        👉  Donate: https://opencollective.com/rubyconfig/donate
>        Post-install message from sucker_punch:
>        Sucker Punch v2.0 introduces backwards-incompatible changes.
>        Please see https://github.com/brandonhilkert/sucker_punch/blob/master/CHANGES.md#200 for details.
>        Removing bundler (2.0.2)
>        Bundle completed (149.99s)
>        Cleaning up the bundler cache.
> -----> Installing node-v10.15.3-linux-x64
> -----> Detecting rake tasks
> -----> Preparing app for Rails asset pipeline
>        Running: rake assets:precompile
>        W, [2020-05-31T19:00:11.403258 #1461]  WARN -- : Creating scope :open. Overwriting existing method Proposal.open.
>        I, [2020-05-31T19:00:12.224060 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/rails_admin-8f99aaf479824886507ab4acabafe75760cca4fde49e5a5c486af877eb348ccc.js
>        I, [2020-05-31T19:00:12.224533 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/rails_admin-8f99aaf479824886507ab4acabafe75760cca4fde49e5a5c486af877eb348ccc.js.gz
>        I, [2020-05-31T19:00:12.949837 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/rails_admin-84f604f4beaec0274f8dd8b028fa501a127efce76b66ce6eb6aa52a0e7d18923.css
>        I, [2020-05-31T19:00:12.952419 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/rails_admin-84f604f4beaec0274f8dd8b028fa501a127efce76b66ce6eb6aa52a0e7d18923.css.gz
>        I, [2020-05-31T19:00:12.953077 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/aristo/images/bg_fallback-bad53cee26694a42bdba717337e2de9f997ebf3ded300b8c3ff48ac5192c1903.png
>        I, [2020-05-31T19:00:12.953699 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/aristo/images/ui-icons_222222_256x240-310ae73efc6774716f0a80ce2141565fddec51702330a8066fd5e220437ae321.png
>        I, [2020-05-31T19:00:12.954493 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/aristo/images/ui-icons_454545_256x240-d59c6da436d1a19aa35bcbf2d400ad160f2b2568fbbfa2f9ebfc192d14025474.png
>        I, [2020-05-31T19:00:12.959236 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/aristo/images/icon_sprite-34a30806fcba43a2effc9739cb7a370a865199a7d38bfcbc7c2474ef3ff70ded.png
>        I, [2020-05-31T19:00:12.964866 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/aristo/images/slider_handles-4b523f3d1bd18af5fec23ec7d58ed85e4c7e8f4685fe85a8407e2d9017bf6484.png
>        I, [2020-05-31T19:00:12.965365 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/aristo/images/progress_bar-a2ed712d76dcffc7a06918cd389511bca2cf7bb91c12b1d865bf44c7b2c46289.gif
>        I, [2020-05-31T19:00:12.965937 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/multiselect/icon_sprite-34a30806fcba43a2effc9739cb7a370a865199a7d38bfcbc7c2474ef3ff70ded.png
>        I, [2020-05-31T19:00:12.966458 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-n-light-e7daf3169259a9fd6b8177b8e89ff2b964cd3dababd580a46d7fb4eecc07763b.png
>        I, [2020-05-31T19:00:12.967007 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-n-dark-bb53269e44173a496d2620bad201ca838a57b67c40b3439b5ce89345ef9e888b.png
>        I, [2020-05-31T19:00:12.967550 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-s-light-e1698d37f37f7db85ce6736810a34b1a229306be8a3f3be156fbaa47dd6cd160.png
>        I, [2020-05-31T19:00:12.969590 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-s-dark-2bf097798e2b1db766a16ff4f335d3fe94bd51f92dc2ddf47c8a370ba31189c0.png
>        I, [2020-05-31T19:00:12.970204 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/select2-8ddf680d1a86d603653e43f694bbb6dc1010aa81f5c0c9c87181e10e064e503b.png
>        I, [2020-05-31T19:00:12.970808 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_background-52967b595ae718ad95520b9cf2b22551fb8cb0d81a171db869b00d2b604b4976.png
>        I, [2020-05-31T19:00:12.971581 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/colorpicker_overlay-ba21ab85c59167b61af508e34a22ee344c97bb11454d287a47691fa2fb182856.png
>        I, [2020-05-31T19:00:12.972370 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/colorpicker_select-980ae86d6aab751f6f67a1191d78c0fa54b533583456b905ec43b34d5806ee2d.gif
>        I, [2020-05-31T19:00:12.973071 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_indic-8ca62ee85015e67671f2312a2fead633740335f65e254d8f4c3ea29b99f62de7.gif
>        I, [2020-05-31T19:00:12.973855 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_hex-4b1a7b08312edc3732cf30c7d8d5291abea41c64311c3d05d67a586cbe3dcf37.png
>        I, [2020-05-31T19:00:12.974589 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_rgb_r-54289ccad89df00514d84ba6d16d1a0abc0d61de95dcfc054bf2202e238a7cb6.png
>        I, [2020-05-31T19:00:12.975374 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_rgb_g-8ab4d41c46fc26080b75eecc6f8c25d8f6db5264cf56ecc4993f86d100ebd71f.png
>        I, [2020-05-31T19:00:12.977492 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_rgb_b-22f2da1810cd9da18a1f93418b8f45bd3cb676aa9790ad5e1aba37779fb3ac31.png
>        I, [2020-05-31T19:00:12.977990 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_hsb_h-df01edb80a710cdd9d9057201eaa682a8c86cd80ad6c6929f1d4a9182ad6aed3.png
>        I, [2020-05-31T19:00:12.980453 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_hsb_s-9277f3fd9eb79baef2384f7b38968184fd40d631024149c7b41543b7796c0706.png
>        I, [2020-05-31T19:00:12.981598 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_hsb_b-7160b5fd5c5779102cb91f771b80ef2621dabe10bf06e8359deaefece831b58b.png
>        I, [2020-05-31T19:00:12.983077 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/colorpicker/custom_submit-3a57bad878f6d608b998e36acefe2325d786d4631abeecc5d400ca5c062f5ce5.png
>        I, [2020-05-31T19:00:12.984746 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot
>        I, [2020-05-31T19:00:12.985570 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot.gz
>        I, [2020-05-31T19:00:12.986203 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe.woff2
>        I, [2020-05-31T19:00:12.991255 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff
>        I, [2020-05-31T19:00:12.992038 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf
>        I, [2020-05-31T19:00:12.993032 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf.gz
>        I, [2020-05-31T19:00:12.994375 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg
>        I, [2020-05-31T19:00:12.997832 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg.gz
>        I, [2020-05-31T19:00:13.010296 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/jquery.colorpicker-3a18b8912af93099a30d1cf8f47c1084f093d1d208863a218e28f098f64dbf78.js
>        I, [2020-05-31T19:00:13.010905 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/jquery.colorpicker-3a18b8912af93099a30d1cf8f47c1084f093d1d208863a218e28f098f64dbf78.js.gz
>        I, [2020-05-31T19:00:13.081715 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/jquery.colorpicker-17a04cd55ca585e49dd291bbe9ff1c5dc7ebefc092eac763d85512eba90f4821.css
>        I, [2020-05-31T19:00:13.081864 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/rails_admin/jquery.colorpicker-17a04cd55ca585e49dd291bbe9ff1c5dc7ebefc092eac763d85512eba90f4821.css.gz
>        I, [2020-05-31T19:00:13.086852 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/apple-touch-icon-1137f7c0018cb6073fee4b812f45af2300b11006132850269d998b922a80bf29.png
>        I, [2020-05-31T19:00:13.161198 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/application-fc4e6f2c9fd1a75e45b4034eb1a30144bf6a804df499feaa9c803edf8cc2945b.js
>        I, [2020-05-31T19:00:13.162153 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/application-fc4e6f2c9fd1a75e45b4034eb1a30144bf6a804df499feaa9c803edf8cc2945b.js.gz
>        I, [2020-05-31T19:00:13.311354 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/application-ca014afd1193d5300bbf71295eee80b5ee276f627129e4aaa342ac836be21772.css
>        I, [2020-05-31T19:00:13.311794 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/application-ca014afd1193d5300bbf71295eee80b5ee276f627129e4aaa342ac836be21772.css.gz
>        I, [2020-05-31T19:00:13.312525 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot
>        I, [2020-05-31T19:00:13.313406 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot.gz
>        I, [2020-05-31T19:00:13.316877 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe.woff2
>        I, [2020-05-31T19:00:13.318150 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff
>        I, [2020-05-31T19:00:13.319348 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf
>        I, [2020-05-31T19:00:13.320370 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf.gz
>        I, [2020-05-31T19:00:13.328662 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg
>        I, [2020-05-31T19:00:13.330345 #1461]  INFO -- : Writing /tmp/build_a2c985f9533934b95205cfd32ef9a28e/public/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg.gz
>        Asset precompilation completed (5.69s)
>        Cleaning assets
>        Running: rake assets:clean
>        W, [2020-05-31T19:00:17.055732 #1484]  WARN -- : Creating scope :open. Overwriting existing method Proposal.open.
> -----> Detecting rails configuration
> -----> Discovering process types
>        Procfile declares types     -> web
>        Default types for buildpack -> console, rake
> -----> Compressing...
>        Done: 47.3M
> -----> Launching...
>        Released v12
>        https://openpolitics-test-bot-12391.herokuapp.com/ deployed to Heroku

**Comment by tyumru** [comment]
Removed worker process from apps.json and it started working. IDK if that was essential for a specific function.

**Comment by Floppy** [comment]
Oh, well spotted! The `worker` dyno isn't needed any more, and it should be removed from `app.json`. Thanks for the bug report!
