### ISSUE TITLE
Finishing the consensus democracy set up

### ISSUE THREAD

**Issue by Autumn-Leah** [openpolitics/groupthink#92]
If you're doing consensus democracy, customised to the platform of course, you'll need abstain, block, approve, disapprove (in the sense that you disapprove but you wil not leave the commune, or in this case the party, if it passes), principled disapproval (you'll leave the party if it passes), stand aside (in the sense that you have nothing useful to add yet but you will be watching with a view to contribute), and declaring reservations.

You need abstain so that you can express that you've got no position, or to reset a positive or negative vote or block. Principled disapproval could be done just by saying "if these passes I leave" and could be used for manipulation, so I leave that to your wisdom. Stand aside could be necessary as a statement of "I'm watching this, might respond" so everyone can keep track of party involvement, it could also be automatically entered as a vote the moment you view it, since it's effectively a "viewed" tick. Declaring reservations would just be stating a counterpoint as we do now.

**Comment by Floppy** [comment]
So now we have abstention. The two left on here that we can't currently do are "principled disapproval" and "stand aside". 

Does the "participating" state in the vote record work for stand aside? If you are commenting but not voting, that's counted and shown in the summary, but is it the same thing?

**Comment by Floppy** [comment]
Closing this for now due to inactivity. Feel free to reopen with further comment though.
